//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_canyon_H
#define METASPRITE_canyon_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define canyon_TILE_ORIGIN 0
#define canyon_TILE_W 8
#define canyon_TILE_H 8
#define canyon_WIDTH 160
#define canyon_HEIGHT 144
#define canyon_TILE_COUNT 40
#define canyon_TILES_UNCOMPRESSED_SZ 640
#define canyon_PALETTE_COUNT 1
#define canyon_COLORS_PER_PALETTE 4
#define canyon_TOTAL_COLORS 4
#define canyon_MAP_ATTRIBUTES 0

BANKREF_EXTERN(canyon)

extern const palette_color_t canyon_palettes[4];
extern const uint8_t canyon_tiles[];

extern const unsigned char canyon_map[360];

#endif