//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_game_over_H
#define METASPRITE_game_over_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define game_over_TILE_ORIGIN 0
#define game_over_TILE_W 8
#define game_over_TILE_H 16
#define game_over_WIDTH 80
#define game_over_HEIGHT 16
#define game_over_TILE_COUNT 20
#define game_over_PALETTE_COUNT 1
#define game_over_COLORS_PER_PALETTE 4
#define game_over_TOTAL_COLORS 4
#define game_over_PIVOT_X -8
#define game_over_PIVOT_Y -16
#define game_over_PIVOT_W 80
#define game_over_PIVOT_H 16

BANKREF_EXTERN(game_over)

extern const palette_color_t game_over_palettes[4];
extern const uint8_t game_over_tiles[320];

extern const metasprite_t* const game_over_metasprites[1];

#endif
