//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_intro_credits_data_H
#define METASPRITE_intro_credits_data_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define intro_credits_data_TILE_ORIGIN 0
#define intro_credits_data_TILE_W 8
#define intro_credits_data_TILE_H 8
#define intro_credits_data_WIDTH 160
#define intro_credits_data_HEIGHT 144
#define intro_credits_data_TILE_COUNT 89
#define intro_credits_data_PALETTE_COUNT 1
#define intro_credits_data_COLORS_PER_PALETTE 2
#define intro_credits_data_TOTAL_COLORS 2
#define intro_credits_data_MAP_ATTRIBUTES 0

BANKREF_EXTERN(intro_credits_data)

extern const palette_color_t intro_credits_data_palettes[2];
extern const uint8_t intro_credits_data_tiles[712];

extern const unsigned char intro_credits_data_map[360];

#endif
