//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_map_canyon_H
#define METASPRITE_map_canyon_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define map_canyon_TILE_ORIGIN 0
#define map_canyon_TILE_W 8
#define map_canyon_TILE_H 8
#define map_canyon_WIDTH 160
#define map_canyon_HEIGHT 256
#define map_canyon_TILE_COUNT 48
#define map_canyon_PALETTE_COUNT 1
#define map_canyon_COLORS_PER_PALETTE 4
#define map_canyon_TOTAL_COLORS 4
#define map_canyon_MAP_ATTRIBUTES 0

BANKREF_EXTERN(map_canyon)

extern const palette_color_t map_canyon_palettes[4];
extern const uint8_t map_canyon_tiles[768];

extern const unsigned char map_canyon_map[640];

#endif