//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_megaduck_on_ap_data_H
#define METASPRITE_megaduck_on_ap_data_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define megaduck_on_ap_data_TILE_ORIGIN 0
#define megaduck_on_ap_data_TILE_W 8
#define megaduck_on_ap_data_TILE_H 8
#define megaduck_on_ap_data_WIDTH 80
#define megaduck_on_ap_data_HEIGHT 96
#define megaduck_on_ap_data_TILE_COUNT 68
#define megaduck_on_ap_data_PALETTE_COUNT 1
#define megaduck_on_ap_data_COLORS_PER_PALETTE 2
#define megaduck_on_ap_data_TOTAL_COLORS 2
#define megaduck_on_ap_data_MAP_ATTRIBUTES 0

BANKREF_EXTERN(megaduck_on_ap_data)

extern const palette_color_t megaduck_on_ap_data_palettes[2];
extern const uint8_t megaduck_on_ap_data_tiles[544];

extern const unsigned char megaduck_on_ap_data_map[120];
#define megaduck_on_ap_data_map_attributes megaduck_on_ap_data_map

#endif
