//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_splash_logo_data_H
#define METASPRITE_splash_logo_data_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define splash_logo_data_TILE_ORIGIN 0
#define splash_logo_data_TILE_W 8
#define splash_logo_data_TILE_H 8
#define splash_logo_data_WIDTH 168
#define splash_logo_data_HEIGHT 104
#define splash_logo_data_TILE_COUNT 175
#define splash_logo_data_PALETTE_COUNT 1
#define splash_logo_data_COLORS_PER_PALETTE 4
#define splash_logo_data_TOTAL_COLORS 4
#define splash_logo_data_MAP_ATTRIBUTES 0

BANKREF_EXTERN(splash_logo_data)

extern const palette_color_t splash_logo_data_palettes[4];
extern const uint8_t splash_logo_data_tiles[2800];

extern const unsigned char splash_logo_data_map[273];
#define splash_logo_data_map_attributes splash_logo_data_map

#endif
