//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_splash_logo_H
#define METASPRITE_splash_logo_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define splash_logo_TILE_ORIGIN 0
#define splash_logo_TILE_W 8
#define splash_logo_TILE_H 8
#define splash_logo_WIDTH 168
#define splash_logo_HEIGHT 96
#define splash_logo_TILE_COUNT 173
#define splash_logo_PALETTE_COUNT 1
#define splash_logo_COLORS_PER_PALETTE 4
#define splash_logo_TOTAL_COLORS 4
#define splash_logo_MAP_ATTRIBUTES 0

BANKREF_EXTERN(splash_logo)

extern const palette_color_t splash_logo_palettes[4];
extern const uint8_t splash_logo_tiles[2768];

extern const unsigned char splash_logo_map[252];

#endif