//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sprite_sound_test_cursor_H
#define METASPRITE_sprite_sound_test_cursor_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sprite_sound_test_cursor_TILE_ORIGIN 0
#define sprite_sound_test_cursor_TILE_W 8
#define sprite_sound_test_cursor_TILE_H 8
#define sprite_sound_test_cursor_WIDTH 8
#define sprite_sound_test_cursor_HEIGHT 8
#define sprite_sound_test_cursor_TILE_COUNT 1
#define sprite_sound_test_cursor_PALETTE_COUNT 1
#define sprite_sound_test_cursor_COLORS_PER_PALETTE 4
#define sprite_sound_test_cursor_TOTAL_COLORS 4
#define sprite_sound_test_cursor_PIVOT_X 4
#define sprite_sound_test_cursor_PIVOT_Y 4
#define sprite_sound_test_cursor_PIVOT_W 8
#define sprite_sound_test_cursor_PIVOT_H 8

BANKREF_EXTERN(sprite_sound_test_cursor)

extern const palette_color_t sprite_sound_test_cursor_palettes[4];
extern const uint8_t sprite_sound_test_cursor_tiles[16];

extern const metasprite_t* const sprite_sound_test_cursor_metasprites[1];

#endif
