//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sprite_pause_H
#define METASPRITE_sprite_pause_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sprite_pause_TILE_ORIGIN 0
#define sprite_pause_TILE_W 8
#define sprite_pause_TILE_H 16
#define sprite_pause_WIDTH 8
#define sprite_pause_HEIGHT 16
#define sprite_pause_TILE_COUNT 10
#define sprite_pause_PALETTE_COUNT 1
#define sprite_pause_COLORS_PER_PALETTE 4
#define sprite_pause_TOTAL_COLORS 4

BANKREF_EXTERN(sprite_pause)

extern const palette_color_t sprite_pause_palettes[4];
extern const uint8_t sprite_pause_tiles[160];


#endif
