//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sprite_ready_H
#define METASPRITE_sprite_ready_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sprite_ready_TILE_ORIGIN 0
#define sprite_ready_TILE_W 8
#define sprite_ready_TILE_H 16
#define sprite_ready_WIDTH 8
#define sprite_ready_HEIGHT 16
#define sprite_ready_TILE_COUNT 10
#define sprite_ready_PALETTE_COUNT 1
#define sprite_ready_COLORS_PER_PALETTE 4
#define sprite_ready_TOTAL_COLORS 4

BANKREF_EXTERN(sprite_ready)

extern const palette_color_t sprite_ready_palettes[4];
extern const uint8_t sprite_ready_tiles[160];


#endif
