//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(sprite_sound_test_cursor)

const palette_color_t sprite_sound_test_cursor_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(248,248,248), RGB8(224,156,129), RGB8( 42,127,  0)
	
};

const uint8_t sprite_sound_test_cursor_tiles[16] = {
	0x00,0x00,0x3e,0x00,
	0x22,0x00,0x22,0x00,
	0x66,0x00,0xaa,0x00,
	0x44,0x00,0x00,0x00
	
};

const metasprite_t sprite_sound_test_cursor_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const sprite_sound_test_cursor_metasprites[1] = {
	sprite_sound_test_cursor_metasprite0
};
