//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tiles_font_nums_bg_H
#define METASPRITE_tiles_font_nums_bg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tiles_font_nums_bg_TILE_ORIGIN 0
#define tiles_font_nums_bg_TILE_W 8
#define tiles_font_nums_bg_TILE_H 8
#define tiles_font_nums_bg_WIDTH 80
#define tiles_font_nums_bg_HEIGHT 8
#define tiles_font_nums_bg_TILE_COUNT 10
#define tiles_font_nums_bg_PALETTE_COUNT 1
#define tiles_font_nums_bg_COLORS_PER_PALETTE 4
#define tiles_font_nums_bg_TOTAL_COLORS 4

BANKREF_EXTERN(tiles_font_nums_bg)

extern const palette_color_t tiles_font_nums_bg_palettes[4];
extern const uint8_t tiles_font_nums_bg_tiles[160];


#endif