//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tiles_font_nums_H
#define METASPRITE_tiles_font_nums_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tiles_font_nums_TILE_ORIGIN 0
#define tiles_font_nums_TILE_W 8
#define tiles_font_nums_TILE_H 16
#define tiles_font_nums_WIDTH 8
#define tiles_font_nums_HEIGHT 16
#define tiles_font_nums_TILE_COUNT 22
#define tiles_font_nums_PALETTE_COUNT 1
#define tiles_font_nums_COLORS_PER_PALETTE 4
#define tiles_font_nums_TOTAL_COLORS 4

BANKREF_EXTERN(tiles_font_nums)

extern const palette_color_t tiles_font_nums_palettes[4];
extern const uint8_t tiles_font_nums_tiles[352];


#endif
